name: AMLS_II_assignment
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.7
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - adversarial-robustness-toolbox==1.17.1
      - art==6.1
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - gast==0.5.4
      - google-auth==2.27.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - joblib==1.3.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.2
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - numpy==1.26.3
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.0
      - patchify==0.2.3
      - pillow==10.2.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.4
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - six==1.16.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.2
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
# prefix: /Users/anlly/anaconda3/envs/AMLS_II_assignment
